import { Timestamp } from 'firebase/firestore';

export type DeliveryCarrier = 'UPS' | 'USPS' | 'FedEx' | 'Amazon' | 'DHL' | 'Internal Transfer' | 'Other';
export type DeliveryStatus = 'Pending' | 'Arrived' | 'Delivered to Recipient' | 'Returned';

export interface Delivery {
  id: string; // Auto-generated by Firestore
  poId?: string; // Reference to a Purchase Order
  trackingNumber: string;
  carrier: DeliveryCarrier;
  
  // Who is the package for?
  recipientName: string;
  recipientStaffId?: string; // Optional link to internal staff
  
  status: DeliveryStatus;
  notes: string;
  
  trackingUrl?: string; // Optional if we parse the tracking number
  
  // Timestamps
  createdAt: Timestamp;       // When logged into the system
  updatedAt: Timestamp;       // Last metadata change
  resolvedAt?: Timestamp;     // When handed over to recipient or returned
  
  // Audit details
  loggedByTitle: string;      // E.g., 'Front Desk'
  loggedById: string;         // E.g., staffId of person receiving it
}
